server.port: 5000

spring:
  datasource:
      url: ${dbUrl}
      username: ${dbUsername}
      password: ${dbPassword}
  jpa:
      database-platform: ${dbDatabasePlatform}
      hibernate.ddl-auto: ${dbHibernateDdlAuto}

# time in minutes
security.jwt:
  tokenExpirationTime: 600
  tokenIssuer: http://weststeincard.com
  tokenSigningKey: xt8EV6Hy5RMFK4EEuCIDAw7us

logging.level:
  org.springframework.web: DEBUG
  org.springframework.security: DEBUG
  com.weststein.integration.PersonResource: DEBUG
spring.mvc.dispatch-options-request: true
# Dispatch OPTIONS requests to the FrameworkServlet doService method.

solaris:
  token: 2s7c2eeldhlr20t8ayf7pp559tyu8x3mzjc865wn7agkjucn464w4vfimw56ol7kola881
  hook:
    identification: 9f0c4103fd64ea34ee4ecb1bca8892bd
    booking: 23rhd3rw4hjbjhbuwiwlwebflwef
